### ISSUE TITLE
Having a hard time determining what SubPlz does

### ISSUE THREAD

**Issue by etherealite** [kanjieater/AudiobookTextSync#16]
Based on the README.md I am having hard time figuring out what this project does. 

At first glance it's hard to tell if this is simply a wrapper around whisper to generate new subs and or is it a wrapper around alass  if you already have subs. It appears to me that it is doing more than those things. 

It appears to me that SubPlz will generate a timing reference using whisper and then use that with alass to sync your original subs. Am I correct on that?

I think defining the types of scenarios that this tool is meant to handle in the beginning of the readme would be helpful.

Perhaps something like:
```
Easily generate, sync, and manage subtitle files for any media type with special features for working with audiobooks and videos.

## Features
- **Sync Existing Subtitles**: By integrating multiple techniques to synchronize your subtitles, SubPlz lets you select and apply the most accurate method available.
- **Create New Subtitles**: Generate new subtitles from the audio of any media file.
- **File Management**: Automatically organize and rename your subtitles to match your media files.
- **Video Subtitle Swapping**: Easily swap which subtitles are applied to a video file in your media player.
- **Accurately Subtitle Narrated Media**: Leverage the original source text of an ebook to provide highly accurate subtitles.
```

These features could than be further described with references to the underlying technologies.

**Comment by kanjieater** [comment]
Thanks for the feedback. I think you got things mostly right. I shifted things around and tried to clarify more appropriately.
I should really probably just make a video at some point.

![image](https://github.com/user-attachments/assets/03025f94-989a-4c1c-8f4d-637732c34feb)
Here's the updated readme, I hope this helps.

**Comment by etherealite** [comment]
Yeah, this really clears it up for me thanks.

Looks like SubPlz has a nearly all of the features I need for my work flow. Until I saw this project, I was writing some of my own tooling. Going to give this a try instead because it really is a ton of work.

You mention using Bazaar, are you planning on incorporating fetching and matching jimaku.cc sub files from within SubPlz without the need for Bazaar?

**Comment by kanjieater** [comment]
Great! No I have no intention to replicate the bazarr functionality since I'm finding it to work quit well with Jimaku already after the latest release.

Currently subplz only runs on a single directory or file, nonrecursively. The next major piece that I see being incorporated is some form of automation to run subplz on an ongoing basis on a library of nested content to keep subs up to date as media comes in. We would still rely on bazarr or other sources to supply the initial subs, but provide the alignment options subtitle files based off of those initial subs.

If anyone has comments or ideas feel free to discuss them with me on discord, linked in the readme. I'd certainly welcome others contributions and ideas. I think we can probably close this issue for now.

**Comment by etherealite** [comment]
Will do, I'll move it to discord.
